# -*- coding: utf-8 -*-
#
#    James Kuszlewicz
#    August 17th 2017
#    Goettingen, Germany
#
#  This is a YAML configuration file for Clumpiness project.
#  (Inspired by the configuration file for K2_pipes!)
#

#run: TESS-CA1
#run: K2GAP
#run: K2GAPC2
#run: K2GAP
#run: kepFull
#run: fullAPOKASC
run: fullAPOKASC
#run: K2C2
#run: K2GAPC15
#1000stars
#run: TESS_SECTOR_1
#run: TESS_SECTOR_2


#work_dir: '/scratch/seismo/kuszlewicz/Clumpiness-refactor/Code/' #'/scratch/seismo/kuszlewicz/Clumpiness-package/Code/'
work_dir: '/mnt/seismo/scratch/seismo/kuszlewicz/Clumpiness-refactor/Code/' #'/scratch/seismo/kuszlewicz/Clumpiness-package/Code/'
ignore_warnings: False

KEPSEISMIC:
    #output_dir:  '/scratch/seismo/kuszlewicz/Clumpiness-refactor/Data/KEPSEISMIC/' 
    output_dir: '/mnt/seismo/scratch/seismo/kuszlewicz/Clumpiness-refactor/Data/KEPSEISMIC/'
    data_dir: '/mnt/seismo/scratch/seismo/kuszlewicz/Data/Kepseismic/80d_lcs/'
    #data_dir: '/scratch/seismo/kuszlewicz/Data/Kepseismic/80d_lcs/'
    csv_file: 'Kepseismic_kics.csv' #'gap_dr2_epicids.csv'
    data_type: 'kepseismic'
    star_id: 'KIC'
    campaign: 'Kepseismic'
    output: 'output_Kepseismic.csv'

APOK2:
    output_dir:  '/media/kuszlewicz/Work/Clumpiness-backup/Clumpiness-refactor/Data/APOK2/' #'/mnt/seismo/scratch/seismo/kuszlewicz/Clumpiness-refactor/Data/APOK2/'
    data_dir: '/mnt/seismo/scratch/seismo/kuszlewicz/APOK2_data/'
    csv_file: 'dr2_2_plus_pipeline_ids.csv' #'gap_dr2_epicids.csv'
    data_type: 'EVEREST'
    star_id: 'EPIC'
    campaign: 'APOK2'
    output: 'output_APOK2.csv'

TESS_SECTOR_1:
    output_dir: '/scratch/seismo/kuszlewicz/Clumpiness-package/Data/TESS_SECTOR_1/'
    data_dir: '/scratch/seismo/bell/TESS_data/Sector_1_LCs/'
    csv_file: 'TESS_S1.csv'
    star_id: 'TIC'
    campaign: 'None'
    output: 'output_TESS_S1.csv'

TESS_SECTOR_2:
    output_dir: '/scratch/seismo/kuszlewicz/Clumpiness-package/Data/TESS_SECTOR_2/'
    data_dir: '/scratch/seismo/bell/TESS_data/Sector_2_LCs/'
    csv_file: 'TESS_S2.csv'
    star_id: 'TIC'
    campaign: 'None'
    output: 'output_TESS_S2.csv'

K2C2:
    output_dir: '/mnt/seismo/scratch/seismo/kuszlewicz/Clumpiness-refactor/Tables/'
    data_dir: '/mnt/seismo/scratch/seismo/bell/K2Data_Everest/c2/'
    csv_file: 'k2_c2_dr2_4arcsec.csv'
    star_id: 'EPIC'
    data_type: 'K2'
    campaign: '2'
    output: 'output_K2C2.csv'   

kepFull:
    output_dir: '/scratch/seismo/kuszlewicz/Clumpiness-package/Data/kepFull/'
#    data_dir: '/scratch/seismo/bell/Kepler_ALL/stitchedlcs/'
    data_dir: '/scratch/seismo/kuszlewicz/Data/Full_lcs/'  
    csv_file: 'fullKepler.csv'
    data_type: 'fullKep'
    star_id: 'KIC'
    campaign: 'None'
    output: 'output_kepfull.csv'

HD203949:
    output_dir: '/scratch/seismo/kuszlewicz/Clumpiness-refactor/Code/HD203949/'
    data_dir: '/scratch/seismo/kuszlewicz/Clumpiness-refactor/Code/HD2039494/'
    csv_file: 'HD203959.csv'
    data_type: 'TESS'
    star_id: 'TIC'
    campaign: 'None'
    output: 'HD203949_output.csv'

fullAPOKASC:
    output_dir: '../Data/APOKASCstars/'
#    data_dir: '/home/kuszlewicz/Dropbox/Data/Kepler/APOKASC_DR1_ts/'
#    data_dir: '/scratch/seismo/bell/Kepler_ALL/stitchedlcs/'
    data_dir: '/scratch/seismo/kuszlewicz/Data/Full_lcs/'
#    data_dir: '/mnt/seismo/scratch/seismo/kuszlewicz/Data/Full_lcs/'
    ps_dir: '/home/kuszlewicz/Dropbox/Data/Kepler/APOKASC_DR1_unweighted/'
    csv_file: 'fullAPOKASC.csv' #'APOKASCstars.csv'
    data_type: 'APOKASC'
    star_id: 'KIC'
    campaign: 'None'
    output: 'output_fullAPOKASC.csv'


TESS-CA1:
    output_dir: '/home/kuszlewicz/Dropbox/Python/Clumpiness-package/Data/TESS-CA1/'
    #data_dir: '/home/kuszlewicz/Dropbox/Python/TDA3-classification/Data/cleaned_clean_data/'
    data_dir: '/home/kuszlewicz/Dropbox/Python/TDA3-classification/Data/cleaned_noisy_data/'
    csv_file: 'TESS-CA1.csv'
    star_id: 'Star'
    data_type: 'None'
    campaign: 'TCA1'
    output: 'output_TESS-CA1.csv'
    #output: 'output_TESS-CA1_noisy.csv'

K2GAP:
    output_dir: '/home/kuszlewicz/Dropbox/Python/Clumpiness-package/Data/K2GAP_test/'
    data_dir: '/home/kuszlewicz/Dropbox/Python/K2-Clumpiness/C1/everest/'
    csv_file: 'K2GAPstars.csv'
    data_type: 'EVEREST'
    star_id: 'EPIC'
    campaign: 'C1'
    output: 'output_K2GAP.csv'

K2GAPC2:
    output_dir: '/home/kuszlewicz/Dropbox/Python/Clumpiness-package/Data/K2GAPC2_test/'
    data_dir: '/home/kuszlewicz/Dropbox/Python/K2-Clumpiness/C2/'
    csv_file: 'K2GAPC2stars.csv'
    data_type: 'EVEREST'
    star_id: 'EPIC'
    campaign: 'C2'
    output: 'output_K2GAP.csv'

K2GAPC15:
    output_dir: '/home/kuszlewicz/Dropbox/Python/Clumpiness-package/Data/K2GAPC15_test/'
    data_dir: '/home/kuszlewicz/Dropbox/Python/K2-Clumpiness/C15/K2SFF'
    data_type: 'K2SFF'
    csv_file: 'K2GAPC15stars.csv'
    star_id: 'EPIC'
    campaign: 'C15'
    output: 'output_K2GAP.csv'
