# -*- coding: utf-8 -*-
#
#    James Kuszlewicz
#    August 17th 2017
#    Goettingen, Germany
#
#  This is a YAML configuration file for Clumpiness project.
#  (Inspired by the configuration file for K2_pipes!)
#

run: fullAPOKASC

work_dir: '/mnt/seismo/scratch/seismo/kuszlewicz/Clumpiness-refactor/Code/'
ignore_warnings: False

KEPSEISMIC:
    #output_dir:  '/scratch/seismo/kuszlewicz/Clumpiness-refactor/Data/KEPSEISMIC/' 
    output_dir: '/mnt/seismo/scratch/seismo/kuszlewicz/Clumpiness-refactor/Data/KEPSEISMIC/'
    data_dir: '/mnt/seismo/scratch/seismo/kuszlewicz/Data/Kepseismic/80d_lcs/'
    #data_dir: '/scratch/seismo/kuszlewicz/Data/Kepseismic/80d_lcs/'
    csv_file: 'Kepseismic_kics.csv' #'gap_dr2_epicids.csv'
    data_type: 'kepseismic'
    star_id: 'KIC'
    campaign: 'Kepseismic'
    output: 'output_Kepseismic.csv'

APOK2:
    output_dir:  '/media/kuszlewicz/Work/Clumpiness-backup/Clumpiness-refactor/Data/APOK2/' #'/mnt/seismo/scratch/seismo/kuszlewicz/Clumpiness-refactor/Data/APOK2/'
    data_dir: '/mnt/seismo/scratch/seismo/kuszlewicz/APOK2_data/'
    csv_file: 'dr2_2_plus_pipeline_ids.csv' #'gap_dr2_epicids.csv'
    data_type: 'EVEREST'
    star_id: 'EPIC'
    campaign: 'APOK2'
    output: 'output_APOK2.csv'

kepFull:
    output_dir: '/scratch/seismo/kuszlewicz/Clumpiness-package/Data/kepFull/'
#    data_dir: '/scratch/seismo/bell/Kepler_ALL/stitchedlcs/'
    data_dir: '/scratch/seismo/kuszlewicz/Data/Full_lcs/'  
    csv_file: 'fullKepler.csv'
    data_type: 'fullKep'
    star_id: 'KIC'
    campaign: 'None'
    output: 'output_kepfull.csv'

fullAPOKASC:
    output_dir: '../Data/APOKASCstars/'
#    data_dir: '/home/kuszlewicz/Dropbox/Data/Kepler/APOKASC_DR1_ts/'
#    data_dir: '/scratch/seismo/bell/Kepler_ALL/stitchedlcs/'
    data_dir: '/scratch/seismo/kuszlewicz/Data/Full_lcs/'
#    data_dir: '/mnt/seismo/scratch/seismo/kuszlewicz/Data/Full_lcs/'
    ps_dir: '/home/kuszlewicz/Dropbox/Data/Kepler/APOKASC_DR1_unweighted/'
    csv_file: 'fullAPOKASC.csv' #'APOKASCstars.csv'
    data_type: 'APOKASC'
    star_id: 'KIC'
    campaign: 'None'
    output: 'output_fullAPOKASC.csv'